/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/404': RouteRecordInfo<
      '/404',
      '/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/': RouteRecordInfo<
      '/about/',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/site': RouteRecordInfo<
      '/about/site',
      '/about/site',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/archives/': RouteRecordInfo<
      '/archives/',
      '/archives',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/categories/': RouteRecordInfo<
      '/categories/',
      '/categories',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/links/': RouteRecordInfo<
      '/links/',
      '/links',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/page/[page]': RouteRecordInfo<
      '/page/[page]',
      '/page/:page',
      { page: ParamValue<true> },
      { page: ParamValue<false> },
      | never
    >,
    '/posts/': RouteRecordInfo<
      '/posts/',
      '/posts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/ac-automaton-template': RouteRecordInfo<
      '/posts/ac-automaton-template',
      '/posts/ac-automaton-template',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/algorithm-problem-solving-notes': RouteRecordInfo<
      '/posts/algorithm-problem-solving-notes',
      '/posts/algorithm-problem-solving-notes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/atcoder-dp-training': RouteRecordInfo<
      '/posts/atcoder-dp-training',
      '/posts/atcoder-dp-training',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/binomial-coefficient-template': RouteRecordInfo<
      '/posts/binomial-coefficient-template',
      '/posts/binomial-coefficient-template',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cf-a-and-b-and-lecture-rooms': RouteRecordInfo<
      '/posts/cf-a-and-b-and-lecture-rooms',
      '/posts/cf-a-and-b-and-lecture-rooms',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cf-ant-colony': RouteRecordInfo<
      '/posts/cf-ant-colony',
      '/posts/cf-ant-colony',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cf-array-shrinking': RouteRecordInfo<
      '/posts/cf-array-shrinking',
      '/posts/cf-array-shrinking',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cf-beautiful-sequence': RouteRecordInfo<
      '/posts/cf-beautiful-sequence',
      '/posts/cf-beautiful-sequence',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cf-beppa-and-swerchat': RouteRecordInfo<
      '/posts/cf-beppa-and-swerchat',
      '/posts/cf-beppa-and-swerchat',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cf-binary-median': RouteRecordInfo<
      '/posts/cf-binary-median',
      '/posts/cf-binary-median',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cf-block-sequence': RouteRecordInfo<
      '/posts/cf-block-sequence',
      '/posts/cf-block-sequence',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cf-boris-and-his-amazing-haircut': RouteRecordInfo<
      '/posts/cf-boris-and-his-amazing-haircut',
      '/posts/cf-boris-and-his-amazing-haircut',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cf-calendar-ambiguity': RouteRecordInfo<
      '/posts/cf-calendar-ambiguity',
      '/posts/cf-calendar-ambiguity',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cf-canal-crossing': RouteRecordInfo<
      '/posts/cf-canal-crossing',
      '/posts/cf-canal-crossing',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cf-ceil-divisions': RouteRecordInfo<
      '/posts/cf-ceil-divisions',
      '/posts/cf-ceil-divisions',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cf-check-transcription': RouteRecordInfo<
      '/posts/cf-check-transcription',
      '/posts/cf-check-transcription',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cf-coloring-edges': RouteRecordInfo<
      '/posts/cf-coloring-edges',
      '/posts/cf-coloring-edges',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cf-data-structures-fan': RouteRecordInfo<
      '/posts/cf-data-structures-fan',
      '/posts/cf-data-structures-fan',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cf-destroy-it': RouteRecordInfo<
      '/posts/cf-destroy-it',
      '/posts/cf-destroy-it',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cf-distance-to-different': RouteRecordInfo<
      '/posts/cf-distance-to-different',
      '/posts/cf-distance-to-different',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cf-dogeforces': RouteRecordInfo<
      '/posts/cf-dogeforces',
      '/posts/cf-dogeforces',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cf-eliminating-balls-with-merging-easy-version': RouteRecordInfo<
      '/posts/cf-eliminating-balls-with-merging-easy-version',
      '/posts/cf-eliminating-balls-with-merging-easy-version',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cf-fibonacci-paths': RouteRecordInfo<
      '/posts/cf-fibonacci-paths',
      '/posts/cf-fibonacci-paths',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cf-final-boss': RouteRecordInfo<
      '/posts/cf-final-boss',
      '/posts/cf-final-boss',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cf-frog-jumping': RouteRecordInfo<
      '/posts/cf-frog-jumping',
      '/posts/cf-frog-jumping',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cf-garage': RouteRecordInfo<
      '/posts/cf-garage',
      '/posts/cf-garage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cf-git-gud': RouteRecordInfo<
      '/posts/cf-git-gud',
      '/posts/cf-git-gud',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cf-graph-composition': RouteRecordInfo<
      '/posts/cf-graph-composition',
      '/posts/cf-graph-composition',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cf-inversion-pairs': RouteRecordInfo<
      '/posts/cf-inversion-pairs',
      '/posts/cf-inversion-pairs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cf-jewels-building': RouteRecordInfo<
      '/posts/cf-jewels-building',
      '/posts/cf-jewels-building',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cf-juggling-keys': RouteRecordInfo<
      '/posts/cf-juggling-keys',
      '/posts/cf-juggling-keys',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cf-legacy': RouteRecordInfo<
      '/posts/cf-legacy',
      '/posts/cf-legacy',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cf-lucky-country': RouteRecordInfo<
      '/posts/cf-lucky-country',
      '/posts/cf-lucky-country',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cf-make-it-increasing': RouteRecordInfo<
      '/posts/cf-make-it-increasing',
      '/posts/cf-make-it-increasing',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cf-max-geq-sum': RouteRecordInfo<
      '/posts/cf-max-geq-sum',
      '/posts/cf-max-geq-sum',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cf-max-median': RouteRecordInfo<
      '/posts/cf-max-median',
      '/posts/cf-max-median',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cf-max-sum-or-hard-version': RouteRecordInfo<
      '/posts/cf-max-sum-or-hard-version',
      '/posts/cf-max-sum-or-hard-version',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cf-maximum-value': RouteRecordInfo<
      '/posts/cf-maximum-value',
      '/posts/cf-maximum-value',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cf-merging-towers': RouteRecordInfo<
      '/posts/cf-merging-towers',
      '/posts/cf-merging-towers',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cf-minimum-path': RouteRecordInfo<
      '/posts/cf-minimum-path',
      '/posts/cf-minimum-path',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cf-minimum-spanning-tree-for-each-edge': RouteRecordInfo<
      '/posts/cf-minimum-spanning-tree-for-each-edge',
      '/posts/cf-minimum-spanning-tree-for-each-edge',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cf-mst-unification': RouteRecordInfo<
      '/posts/cf-mst-unification',
      '/posts/cf-mst-unification',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cf-not-a-nim-problem': RouteRecordInfo<
      '/posts/cf-not-a-nim-problem',
      '/posts/cf-not-a-nim-problem',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cf-one-occurrence': RouteRecordInfo<
      '/posts/cf-one-occurrence',
      '/posts/cf-one-occurrence',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cf-openstreetmap': RouteRecordInfo<
      '/posts/cf-openstreetmap',
      '/posts/cf-openstreetmap',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cf-pathwalks': RouteRecordInfo<
      '/posts/cf-pathwalks',
      '/posts/cf-pathwalks',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cf-petya-and-graph': RouteRecordInfo<
      '/posts/cf-petya-and-graph',
      '/posts/cf-petya-and-graph',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cf-power-of-points': RouteRecordInfo<
      '/posts/cf-power-of-points',
      '/posts/cf-power-of-points',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cf-powerful-array': RouteRecordInfo<
      '/posts/cf-powerful-array',
      '/posts/cf-powerful-array',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cf-present': RouteRecordInfo<
      '/posts/cf-present',
      '/posts/cf-present',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cf-rearrange-brackets': RouteRecordInfo<
      '/posts/cf-rearrange-brackets',
      '/posts/cf-rearrange-brackets',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cf-remainder-problem': RouteRecordInfo<
      '/posts/cf-remainder-problem',
      '/posts/cf-remainder-problem',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cf-restricted-sorting': RouteRecordInfo<
      '/posts/cf-restricted-sorting',
      '/posts/cf-restricted-sorting',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cf-round-subset': RouteRecordInfo<
      '/posts/cf-round-subset',
      '/posts/cf-round-subset',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cf-serval-and-the-formula': RouteRecordInfo<
      '/posts/cf-serval-and-the-formula',
      '/posts/cf-serval-and-the-formula',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cf-sheriffs-defense': RouteRecordInfo<
      '/posts/cf-sheriffs-defense',
      '/posts/cf-sheriffs-defense',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cf-shohag-loves-gcd': RouteRecordInfo<
      '/posts/cf-shohag-loves-gcd',
      '/posts/cf-shohag-loves-gcd',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cf-shortest-path-problem': RouteRecordInfo<
      '/posts/cf-shortest-path-problem',
      '/posts/cf-shortest-path-problem',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cf-shortest-path-queries': RouteRecordInfo<
      '/posts/cf-shortest-path-queries',
      '/posts/cf-shortest-path-queries',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cf-shovels-shop': RouteRecordInfo<
      '/posts/cf-shovels-shop',
      '/posts/cf-shovels-shop',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cf-small-gcd': RouteRecordInfo<
      '/posts/cf-small-gcd',
      '/posts/cf-small-gcd',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cf-tree-painting': RouteRecordInfo<
      '/posts/cf-tree-painting',
      '/posts/cf-tree-painting',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cf-trip-to-the-olympiad': RouteRecordInfo<
      '/posts/cf-trip-to-the-olympiad',
      '/posts/cf-trip-to-the-olympiad',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cf-tufurama': RouteRecordInfo<
      '/posts/cf-tufurama',
      '/posts/cf-tufurama',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cf-two-editorials': RouteRecordInfo<
      '/posts/cf-two-editorials',
      '/posts/cf-two-editorials',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cf-we-need-more-bosses': RouteRecordInfo<
      '/posts/cf-we-need-more-bosses',
      '/posts/cf-we-need-more-bosses',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cf-xor-and-favorite-number': RouteRecordInfo<
      '/posts/cf-xor-and-favorite-number',
      '/posts/cf-xor-and-favorite-number',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cf-xor-tree': RouteRecordInfo<
      '/posts/cf-xor-tree',
      '/posts/cf-xor-tree',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/clang-bits-stdcxx-fix': RouteRecordInfo<
      '/posts/clang-bits-stdcxx-fix',
      '/posts/clang-bits-stdcxx-fix',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/connect-ipv6-server': RouteRecordInfo<
      '/posts/connect-ipv6-server',
      '/posts/connect-ipv6-server',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cpp-class-memory-leak': RouteRecordInfo<
      '/posts/cpp-class-memory-leak',
      '/posts/cpp-class-memory-leak',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/ddos-defense-thoughts': RouteRecordInfo<
      '/posts/ddos-defense-thoughts',
      '/posts/ddos-defense-thoughts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/dinic-template': RouteRecordInfo<
      '/posts/dinic-template',
      '/posts/dinic-template',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/docker-notes': RouteRecordInfo<
      '/posts/docker-notes',
      '/posts/docker-notes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/double-hash-map-template': RouteRecordInfo<
      '/posts/double-hash-map-template',
      '/posts/double-hash-map-template',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/dp-problem-solving-tips': RouteRecordInfo<
      '/posts/dp-problem-solving-tips',
      '/posts/dp-problem-solving-tips',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/first-blog-post': RouteRecordInfo<
      '/posts/first-blog-post',
      '/posts/first-blog-post',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/hash-template': RouteRecordInfo<
      '/posts/hash-template',
      '/posts/hash-template',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/hopcroft-karp-template': RouteRecordInfo<
      '/posts/hopcroft-karp-template',
      '/posts/hopcroft-karp-template',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/keep-process-running-in-background': RouteRecordInfo<
      '/posts/keep-process-running-in-background',
      '/posts/keep-process-running-in-background',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/kmp-template': RouteRecordInfo<
      '/posts/kmp-template',
      '/posts/kmp-template',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/kruskal-template': RouteRecordInfo<
      '/posts/kruskal-template',
      '/posts/kruskal-template',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/linear-basis-template': RouteRecordInfo<
      '/posts/linear-basis-template',
      '/posts/linear-basis-template',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/manacher-template': RouteRecordInfo<
      '/posts/manacher-template',
      '/posts/manacher-template',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/matrix-exponentiation-template': RouteRecordInfo<
      '/posts/matrix-exponentiation-template',
      '/posts/matrix-exponentiation-template',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/mcmf-template': RouteRecordInfo<
      '/posts/mcmf-template',
      '/posts/mcmf-template',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/mo-algorithm-template': RouteRecordInfo<
      '/posts/mo-algorithm-template',
      '/posts/mo-algorithm-template',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/multi-color-pair-shortest-path-optimization': RouteRecordInfo<
      '/posts/multi-color-pair-shortest-path-optimization',
      '/posts/multi-color-pair-shortest-path-optimization',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/nat-traversal-tutorial': RouteRecordInfo<
      '/posts/nat-traversal-tutorial',
      '/posts/nat-traversal-tutorial',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/persistent-segment-tree-template': RouteRecordInfo<
      '/posts/persistent-segment-tree-template',
      '/posts/persistent-segment-tree-template',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/rollback-dsu-template': RouteRecordInfo<
      '/posts/rollback-dsu-template',
      '/posts/rollback-dsu-template',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/sam-template': RouteRecordInfo<
      '/posts/sam-template',
      '/posts/sam-template',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/segment-tree-template': RouteRecordInfo<
      '/posts/segment-tree-template',
      '/posts/segment-tree-template',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/sparse-table-template': RouteRecordInfo<
      '/posts/sparse-table-template',
      '/posts/sparse-table-template',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/tarjan-ebcc-template': RouteRecordInfo<
      '/posts/tarjan-ebcc-template',
      '/posts/tarjan-ebcc-template',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/tarjan-template': RouteRecordInfo<
      '/posts/tarjan-template',
      '/posts/tarjan-template',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/tree-path-extreme-template': RouteRecordInfo<
      '/posts/tree-path-extreme-template',
      '/posts/tree-path-extreme-template',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/zkw-segment-tree-template': RouteRecordInfo<
      '/posts/zkw-segment-tree-template',
      '/posts/zkw-segment-tree-template',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tags/': RouteRecordInfo<
      '/tags/',
      '/tags',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'node_modules/.pnpm/valaxy-theme-yun@0.26.13_magicast@0.5.4_vue@3.5.22_typescript@5.9.3_/node_modules/valaxy-theme-yun/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'node_modules/.pnpm/valaxy@1.0.0-rc.6_@babel+parser@7.29.8_@nuxt+kit@3.21.0_magicast@0.5.4__@types+markdown-it@14_msnibtdd5vxaej4oo4355743um/node_modules/valaxy/client/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
      pathParamNames:
        | 'path'
    }
    'pages/404.md': {
      routes:
        | '/404'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/about/index.md': {
      routes:
        | '/about/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/about/site.md': {
      routes:
        | '/about/site'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/archives/index.md': {
      routes:
        | '/archives/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/categories/index.md': {
      routes:
        | '/categories/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/links/index.md': {
      routes:
        | '/links/'
      views:
        | never
      pathParamNames:
        | never
    }
    'node_modules/.pnpm/valaxy-theme-yun@0.26.13_magicast@0.5.4_vue@3.5.22_typescript@5.9.3_/node_modules/valaxy-theme-yun/pages/page/[page].vue': {
      routes:
        | '/page/[page]'
      views:
        | never
      pathParamNames:
        | 'page'
    }
    'node_modules/.pnpm/valaxy-theme-yun@0.26.13_magicast@0.5.4_vue@3.5.22_typescript@5.9.3_/node_modules/valaxy-theme-yun/pages/posts/index.vue': {
      routes:
        | '/posts/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/ac-automaton-template.md': {
      routes:
        | '/posts/ac-automaton-template'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/algorithm-problem-solving-notes.md': {
      routes:
        | '/posts/algorithm-problem-solving-notes'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/atcoder-dp-training.md': {
      routes:
        | '/posts/atcoder-dp-training'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/binomial-coefficient-template.md': {
      routes:
        | '/posts/binomial-coefficient-template'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/cf-a-and-b-and-lecture-rooms.md': {
      routes:
        | '/posts/cf-a-and-b-and-lecture-rooms'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/cf-ant-colony.md': {
      routes:
        | '/posts/cf-ant-colony'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/cf-array-shrinking.md': {
      routes:
        | '/posts/cf-array-shrinking'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/cf-beautiful-sequence.md': {
      routes:
        | '/posts/cf-beautiful-sequence'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/cf-beppa-and-swerchat.md': {
      routes:
        | '/posts/cf-beppa-and-swerchat'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/cf-binary-median.md': {
      routes:
        | '/posts/cf-binary-median'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/cf-block-sequence.md': {
      routes:
        | '/posts/cf-block-sequence'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/cf-boris-and-his-amazing-haircut.md': {
      routes:
        | '/posts/cf-boris-and-his-amazing-haircut'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/cf-calendar-ambiguity.md': {
      routes:
        | '/posts/cf-calendar-ambiguity'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/cf-canal-crossing.md': {
      routes:
        | '/posts/cf-canal-crossing'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/cf-ceil-divisions.md': {
      routes:
        | '/posts/cf-ceil-divisions'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/cf-check-transcription.md': {
      routes:
        | '/posts/cf-check-transcription'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/cf-coloring-edges.md': {
      routes:
        | '/posts/cf-coloring-edges'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/cf-data-structures-fan.md': {
      routes:
        | '/posts/cf-data-structures-fan'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/cf-destroy-it.md': {
      routes:
        | '/posts/cf-destroy-it'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/cf-distance-to-different.md': {
      routes:
        | '/posts/cf-distance-to-different'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/cf-dogeforces.md': {
      routes:
        | '/posts/cf-dogeforces'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/cf-eliminating-balls-with-merging-easy-version.md': {
      routes:
        | '/posts/cf-eliminating-balls-with-merging-easy-version'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/cf-fibonacci-paths.md': {
      routes:
        | '/posts/cf-fibonacci-paths'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/cf-final-boss.md': {
      routes:
        | '/posts/cf-final-boss'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/cf-frog-jumping.md': {
      routes:
        | '/posts/cf-frog-jumping'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/cf-garage.md': {
      routes:
        | '/posts/cf-garage'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/cf-git-gud.md': {
      routes:
        | '/posts/cf-git-gud'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/cf-graph-composition.md': {
      routes:
        | '/posts/cf-graph-composition'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/cf-inversion-pairs.md': {
      routes:
        | '/posts/cf-inversion-pairs'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/cf-jewels-building.md': {
      routes:
        | '/posts/cf-jewels-building'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/cf-juggling-keys.md': {
      routes:
        | '/posts/cf-juggling-keys'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/cf-legacy.md': {
      routes:
        | '/posts/cf-legacy'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/cf-lucky-country.md': {
      routes:
        | '/posts/cf-lucky-country'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/cf-make-it-increasing.md': {
      routes:
        | '/posts/cf-make-it-increasing'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/cf-max-geq-sum.md': {
      routes:
        | '/posts/cf-max-geq-sum'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/cf-max-median.md': {
      routes:
        | '/posts/cf-max-median'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/cf-max-sum-or-hard-version.md': {
      routes:
        | '/posts/cf-max-sum-or-hard-version'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/cf-maximum-value.md': {
      routes:
        | '/posts/cf-maximum-value'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/cf-merging-towers.md': {
      routes:
        | '/posts/cf-merging-towers'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/cf-minimum-path.md': {
      routes:
        | '/posts/cf-minimum-path'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/cf-minimum-spanning-tree-for-each-edge.md': {
      routes:
        | '/posts/cf-minimum-spanning-tree-for-each-edge'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/cf-mst-unification.md': {
      routes:
        | '/posts/cf-mst-unification'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/cf-not-a-nim-problem.md': {
      routes:
        | '/posts/cf-not-a-nim-problem'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/cf-one-occurrence.md': {
      routes:
        | '/posts/cf-one-occurrence'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/cf-openstreetmap.md': {
      routes:
        | '/posts/cf-openstreetmap'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/cf-pathwalks.md': {
      routes:
        | '/posts/cf-pathwalks'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/cf-petya-and-graph.md': {
      routes:
        | '/posts/cf-petya-and-graph'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/cf-power-of-points.md': {
      routes:
        | '/posts/cf-power-of-points'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/cf-powerful-array.md': {
      routes:
        | '/posts/cf-powerful-array'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/cf-present.md': {
      routes:
        | '/posts/cf-present'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/cf-rearrange-brackets.md': {
      routes:
        | '/posts/cf-rearrange-brackets'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/cf-remainder-problem.md': {
      routes:
        | '/posts/cf-remainder-problem'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/cf-restricted-sorting.md': {
      routes:
        | '/posts/cf-restricted-sorting'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/cf-round-subset.md': {
      routes:
        | '/posts/cf-round-subset'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/cf-serval-and-the-formula.md': {
      routes:
        | '/posts/cf-serval-and-the-formula'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/cf-sheriffs-defense.md': {
      routes:
        | '/posts/cf-sheriffs-defense'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/cf-shohag-loves-gcd.md': {
      routes:
        | '/posts/cf-shohag-loves-gcd'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/cf-shortest-path-problem.md': {
      routes:
        | '/posts/cf-shortest-path-problem'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/cf-shortest-path-queries.md': {
      routes:
        | '/posts/cf-shortest-path-queries'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/cf-shovels-shop.md': {
      routes:
        | '/posts/cf-shovels-shop'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/cf-small-gcd.md': {
      routes:
        | '/posts/cf-small-gcd'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/cf-tree-painting.md': {
      routes:
        | '/posts/cf-tree-painting'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/cf-trip-to-the-olympiad.md': {
      routes:
        | '/posts/cf-trip-to-the-olympiad'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/cf-tufurama.md': {
      routes:
        | '/posts/cf-tufurama'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/cf-two-editorials.md': {
      routes:
        | '/posts/cf-two-editorials'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/cf-we-need-more-bosses.md': {
      routes:
        | '/posts/cf-we-need-more-bosses'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/cf-xor-and-favorite-number.md': {
      routes:
        | '/posts/cf-xor-and-favorite-number'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/cf-xor-tree.md': {
      routes:
        | '/posts/cf-xor-tree'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/clang-bits-stdcxx-fix.md': {
      routes:
        | '/posts/clang-bits-stdcxx-fix'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/connect-ipv6-server.md': {
      routes:
        | '/posts/connect-ipv6-server'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/cpp-class-memory-leak.md': {
      routes:
        | '/posts/cpp-class-memory-leak'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/ddos-defense-thoughts.md': {
      routes:
        | '/posts/ddos-defense-thoughts'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/dinic-template.md': {
      routes:
        | '/posts/dinic-template'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/docker-notes.md': {
      routes:
        | '/posts/docker-notes'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/double-hash-map-template.md': {
      routes:
        | '/posts/double-hash-map-template'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/dp-problem-solving-tips.md': {
      routes:
        | '/posts/dp-problem-solving-tips'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/first-blog-post.md': {
      routes:
        | '/posts/first-blog-post'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/hash-template.md': {
      routes:
        | '/posts/hash-template'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/hopcroft-karp-template.md': {
      routes:
        | '/posts/hopcroft-karp-template'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/keep-process-running-in-background.md': {
      routes:
        | '/posts/keep-process-running-in-background'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/kmp-template.md': {
      routes:
        | '/posts/kmp-template'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/kruskal-template.md': {
      routes:
        | '/posts/kruskal-template'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/linear-basis-template.md': {
      routes:
        | '/posts/linear-basis-template'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/manacher-template.md': {
      routes:
        | '/posts/manacher-template'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/matrix-exponentiation-template.md': {
      routes:
        | '/posts/matrix-exponentiation-template'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/mcmf-template.md': {
      routes:
        | '/posts/mcmf-template'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/mo-algorithm-template.md': {
      routes:
        | '/posts/mo-algorithm-template'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/multi-color-pair-shortest-path-optimization.md': {
      routes:
        | '/posts/multi-color-pair-shortest-path-optimization'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/nat-traversal-tutorial.md': {
      routes:
        | '/posts/nat-traversal-tutorial'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/persistent-segment-tree-template.md': {
      routes:
        | '/posts/persistent-segment-tree-template'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/rollback-dsu-template.md': {
      routes:
        | '/posts/rollback-dsu-template'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/sam-template.md': {
      routes:
        | '/posts/sam-template'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/segment-tree-template.md': {
      routes:
        | '/posts/segment-tree-template'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/sparse-table-template.md': {
      routes:
        | '/posts/sparse-table-template'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/tarjan-ebcc-template.md': {
      routes:
        | '/posts/tarjan-ebcc-template'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/tarjan-template.md': {
      routes:
        | '/posts/tarjan-template'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/tree-path-extreme-template.md': {
      routes:
        | '/posts/tree-path-extreme-template'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/zkw-segment-tree-template.md': {
      routes:
        | '/posts/zkw-segment-tree-template'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/tags/index.md': {
      routes:
        | '/tags/'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
