/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/404': RouteRecordInfo<
      '/404',
      '/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/': RouteRecordInfo<
      '/about/',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/site': RouteRecordInfo<
      '/about/site',
      '/about/site',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/archives/': RouteRecordInfo<
      '/archives/',
      '/archives',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/categories/': RouteRecordInfo<
      '/categories/',
      '/categories',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/links/': RouteRecordInfo<
      '/links/',
      '/links',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/page/[page]': RouteRecordInfo<
      '/page/[page]',
      '/page/:page',
      { page: ParamValue<true> },
      { page: ParamValue<false> },
      | never
    >,
    '/posts/': RouteRecordInfo<
      '/posts/',
      '/posts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/"保持进程后台运行的实现方式"': RouteRecordInfo<
      '/posts/"保持进程后台运行的实现方式"',
      '/posts/%22%E4%BF%9D%E6%8C%81%E8%BF%9B%E7%A8%8B%E5%90%8E%E5%8F%B0%E8%BF%90%E8%A1%8C%E7%9A%84%E5%AE%9E%E7%8E%B0%E6%96%B9%E5%BC%8F%22',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/"关于C++的类内存泄漏相关"': RouteRecordInfo<
      '/posts/"关于C++的类内存泄漏相关"',
      '/posts/%22%E5%85%B3%E4%BA%8EC++%E7%9A%84%E7%B1%BB%E5%86%85%E5%AD%98%E6%B3%84%E6%BC%8F%E7%9B%B8%E5%85%B3%22',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/"内网穿透简单教程"': RouteRecordInfo<
      '/posts/"内网穿透简单教程"',
      '/posts/%22%E5%86%85%E7%BD%91%E7%A9%BF%E9%80%8F%E7%AE%80%E5%8D%95%E6%95%99%E7%A8%8B%22',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/"可持久化线段树模版"': RouteRecordInfo<
      '/posts/"可持久化线段树模版"',
      '/posts/%22%E5%8F%AF%E6%8C%81%E4%B9%85%E5%8C%96%E7%BA%BF%E6%AE%B5%E6%A0%91%E6%A8%A1%E7%89%88%22',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/"可撤销并查集模版"': RouteRecordInfo<
      '/posts/"可撤销并查集模版"',
      '/posts/%22%E5%8F%AF%E6%92%A4%E9%94%80%E5%B9%B6%E6%9F%A5%E9%9B%86%E6%A8%A1%E7%89%88%22',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/"哈希模版"': RouteRecordInfo<
      '/posts/"哈希模版"',
      '/posts/%22%E5%93%88%E5%B8%8C%E6%A8%A1%E7%89%88%22',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/"多色点对最短路优化方案"': RouteRecordInfo<
      '/posts/"多色点对最短路优化方案"',
      '/posts/%22%E5%A4%9A%E8%89%B2%E7%82%B9%E5%AF%B9%E6%9C%80%E7%9F%AD%E8%B7%AF%E4%BC%98%E5%8C%96%E6%96%B9%E6%A1%88%22',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/"矩阵快速幂模版"': RouteRecordInfo<
      '/posts/"矩阵快速幂模版"',
      '/posts/%22%E7%9F%A9%E9%98%B5%E5%BF%AB%E9%80%9F%E5%B9%82%E6%A8%A1%E7%89%88%22',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/"线性基模版"': RouteRecordInfo<
      '/posts/"线性基模版"',
      '/posts/%22%E7%BA%BF%E6%80%A7%E5%9F%BA%E6%A8%A1%E7%89%88%22',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/"线段树模版"': RouteRecordInfo<
      '/posts/"线段树模版"',
      '/posts/%22%E7%BA%BF%E6%AE%B5%E6%A0%91%E6%A8%A1%E7%89%88%22',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/"组合数模版"': RouteRecordInfo<
      '/posts/"组合数模版"',
      '/posts/%22%E7%BB%84%E5%90%88%E6%95%B0%E6%A8%A1%E7%89%88%22',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/"莫队模版"': RouteRecordInfo<
      '/posts/"莫队模版"',
      '/posts/%22%E8%8E%AB%E9%98%9F%E6%A8%A1%E7%89%88%22',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/"AC自动机模版"': RouteRecordInfo<
      '/posts/"AC自动机模版"',
      '/posts/%22AC%E8%87%AA%E5%8A%A8%E6%9C%BA%E6%A8%A1%E7%89%88%22',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/"CF题解——C. Beautiful Sequence"': RouteRecordInfo<
      '/posts/"CF题解——C. Beautiful Sequence"',
      '/posts/%22CF%E9%A2%98%E8%A7%A3%E2%80%94%E2%80%94C/%20Beautiful%20Sequence%22',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/"CF题解——C. Restricted Sorting"': RouteRecordInfo<
      '/posts/"CF题解——C. Restricted Sorting"',
      '/posts/%22CF%E9%A2%98%E8%A7%A3%E2%80%94%E2%80%94C/%20Restricted%20Sorting%22',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/"CF题解——C. Serval and The Formula"': RouteRecordInfo<
      '/posts/"CF题解——C. Serval and The Formula"',
      '/posts/%22CF%E9%A2%98%E8%A7%A3%E2%80%94%E2%80%94C/%20Serval%20and%20The%20Formula%22',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/"CF题解——C. Trip to the Olympiad"': RouteRecordInfo<
      '/posts/"CF题解——C. Trip to the Olympiad"',
      '/posts/%22CF%E9%A2%98%E8%A7%A3%E2%80%94%E2%80%94C/%20Trip%20to%20the%20Olympiad%22',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/"CF题解——Canal Crossing"': RouteRecordInfo<
      '/posts/"CF题解——Canal Crossing"',
      '/posts/%22CF%E9%A2%98%E8%A7%A3%E2%80%94%E2%80%94Canal%20Crossing%22',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/"CF题解——Ceil Divisions"': RouteRecordInfo<
      '/posts/"CF题解——Ceil Divisions"',
      '/posts/%22CF%E9%A2%98%E8%A7%A3%E2%80%94%E2%80%94Ceil%20Divisions%22',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/"CF题解——D. Boris and His"': RouteRecordInfo<
      '/posts/"CF题解——D. Boris and His"',
      '/posts/%22CF%E9%A2%98%E8%A7%A3%E2%80%94%E2%80%94D/%20Boris%20and%20His%22',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/"CF题解——D. Fibonacci Paths"': RouteRecordInfo<
      '/posts/"CF题解——D. Fibonacci Paths"',
      '/posts/%22CF%E9%A2%98%E8%A7%A3%E2%80%94%E2%80%94D/%20Fibonacci%20Paths%22',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/"CF题解——D. Max GEQ Sum"': RouteRecordInfo<
      '/posts/"CF题解——D. Max GEQ Sum"',
      '/posts/%22CF%E9%A2%98%E8%A7%A3%E2%80%94%E2%80%94D/%20Max%20GEQ%20Sum%22',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/"CF题解——D. Shohag Loves GCD"': RouteRecordInfo<
      '/posts/"CF题解——D. Shohag Loves GCD"',
      '/posts/%22CF%E9%A2%98%E8%A7%A3%E2%80%94%E2%80%94D/%20Shohag%20Loves%20GCD%22',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/"CF题解——D2 .Max Sum OR (Hard Version)"': RouteRecordInfo<
      '/posts/"CF题解——D2 .Max Sum OR (Hard Version)"',
      '/posts/%22CF%E9%A2%98%E8%A7%A3%E2%80%94%E2%80%94D2%20/Max%20Sum%20OR%20(Hard%20Version)%22',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/"CF题解——Destroy it! "': RouteRecordInfo<
      '/posts/"CF题解——Destroy it! "',
      '/posts/%22CF%E9%A2%98%E8%A7%A3%E2%80%94%E2%80%94Destroy%20it!%20%22',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/"CF题解——E. Block Sequence"': RouteRecordInfo<
      '/posts/"CF题解——E. Block Sequence"',
      '/posts/%22CF%E9%A2%98%E8%A7%A3%E2%80%94%E2%80%94E/%20Block%20Sequence%22',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/"CF题解——E. Calendar Ambiguity"': RouteRecordInfo<
      '/posts/"CF题解——E. Calendar Ambiguity"',
      '/posts/%22CF%E9%A2%98%E8%A7%A3%E2%80%94%E2%80%94E/%20Calendar%20Ambiguity%22',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/"CF题解——E. Data Structures Fan"': RouteRecordInfo<
      '/posts/"CF题解——E. Data Structures Fan"',
      '/posts/%22CF%E9%A2%98%E8%A7%A3%E2%80%94%E2%80%94E/%20Data%20Structures%20Fan%22',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/"CF题解——E. Graph Composition"': RouteRecordInfo<
      '/posts/"CF题解——E. Graph Composition"',
      '/posts/%22CF%E9%A2%98%E8%A7%A3%E2%80%94%E2%80%94E/%20Graph%20Composition%22',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/"CF题解——E. Merging Towers"': RouteRecordInfo<
      '/posts/"CF题解——E. Merging Towers"',
      '/posts/%22CF%E9%A2%98%E8%A7%A3%E2%80%94%E2%80%94E/%20Merging%20Towers%22',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/"CF题解——E. Power of Points"': RouteRecordInfo<
      '/posts/"CF题解——E. Power of Points"',
      '/posts/%22CF%E9%A2%98%E8%A7%A3%E2%80%94%E2%80%94E/%20Power%20of%20Points%22',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/"CF题解——E1. Eliminating Balls With Merging (Easy Version)"': RouteRecordInfo<
      '/posts/"CF题解——E1. Eliminating Balls With Merging (Easy Version)"',
      '/posts/%22CF%E9%A2%98%E8%A7%A3%E2%80%94%E2%80%94E1/%20Eliminating%20Balls%20With%20Merging%20(Easy%20Version)%22',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/"CF题解——F. Final Boss"': RouteRecordInfo<
      '/posts/"CF题解——F. Final Boss"',
      '/posts/%22CF%E9%A2%98%E8%A7%A3%E2%80%94%E2%80%94F/%20Final%20Boss%22',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/"CF题解——F. SheriffsDefense"': RouteRecordInfo<
      '/posts/"CF题解——F. SheriffsDefense"',
      '/posts/%22CF%E9%A2%98%E8%A7%A3%E2%80%94%E2%80%94F/%20SheriffsDefense%22',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/"CF题解——G. Garage"': RouteRecordInfo<
      '/posts/"CF题解——G. Garage"',
      '/posts/%22CF%E9%A2%98%E8%A7%A3%E2%80%94%E2%80%94G/%20Garage%22',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/"CF题解——Git Gud"': RouteRecordInfo<
      '/posts/"CF题解——Git Gud"',
      '/posts/%22CF%E9%A2%98%E8%A7%A3%E2%80%94%E2%80%94Git%20Gud%22',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/"CF题解——H. Beppa and SwerChat"': RouteRecordInfo<
      '/posts/"CF题解——H. Beppa and SwerChat"',
      '/posts/%22CF%E9%A2%98%E8%A7%A3%E2%80%94%E2%80%94H/%20Beppa%20and%20SwerChat%22',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/"CF题解——Inversion Pairs"': RouteRecordInfo<
      '/posts/"CF题解——Inversion Pairs"',
      '/posts/%22CF%E9%A2%98%E8%A7%A3%E2%80%94%E2%80%94Inversion%20Pairs%22',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/"CF题解——Juggling Keys"': RouteRecordInfo<
      '/posts/"CF题解——Juggling Keys"',
      '/posts/%22CF%E9%A2%98%E8%A7%A3%E2%80%94%E2%80%94Juggling%20Keys%22',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/"CF题解——Legacy"': RouteRecordInfo<
      '/posts/"CF题解——Legacy"',
      '/posts/%22CF%E9%A2%98%E8%A7%A3%E2%80%94%E2%80%94Legacy%22',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/"CF题解——Lucky Country"': RouteRecordInfo<
      '/posts/"CF题解——Lucky Country"',
      '/posts/%22CF%E9%A2%98%E8%A7%A3%E2%80%94%E2%80%94Lucky%20Country%22',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/"CF题解——Make It Increasing"': RouteRecordInfo<
      '/posts/"CF题解——Make It Increasing"',
      '/posts/%22CF%E9%A2%98%E8%A7%A3%E2%80%94%E2%80%94Make%20It%20Increasing%22',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/"CF题解——Petya and Graph"': RouteRecordInfo<
      '/posts/"CF题解——Petya and Graph"',
      '/posts/%22CF%E9%A2%98%E8%A7%A3%E2%80%94%E2%80%94Petya%20and%20Graph%22',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/"CF题解——Rearrange Brackets"': RouteRecordInfo<
      '/posts/"CF题解——Rearrange Brackets"',
      '/posts/%22CF%E9%A2%98%E8%A7%A3%E2%80%94%E2%80%94Rearrange%20Brackets%22',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/"CF题解——Shortest Path Queries"': RouteRecordInfo<
      '/posts/"CF题解——Shortest Path Queries"',
      '/posts/%22CF%E9%A2%98%E8%A7%A3%E2%80%94%E2%80%94Shortest%20Path%20Queries%22',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/"CF题解——Small GCD"': RouteRecordInfo<
      '/posts/"CF题解——Small GCD"',
      '/posts/%22CF%E9%A2%98%E8%A7%A3%E2%80%94%E2%80%94Small%20GCD%22',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/"CF题解——Tufurama"': RouteRecordInfo<
      '/posts/"CF题解——Tufurama"',
      '/posts/%22CF%E9%A2%98%E8%A7%A3%E2%80%94%E2%80%94Tufurama%22',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/"DInic模版"': RouteRecordInfo<
      '/posts/"DInic模版"',
      '/posts/%22DInic%E6%A8%A1%E7%89%88%22',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/"DoubleHashMap模版"': RouteRecordInfo<
      '/posts/"DoubleHashMap模版"',
      '/posts/%22DoubleHashMap%E6%A8%A1%E7%89%88%22',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/"HopcroftKarp模版"': RouteRecordInfo<
      '/posts/"HopcroftKarp模版"',
      '/posts/%22HopcroftKarp%E6%A8%A1%E7%89%88%22',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/"J. Jewels Building"': RouteRecordInfo<
      '/posts/"J. Jewels Building"',
      '/posts/%22J/%20Jewels%20Building%22',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/"KMP模版"': RouteRecordInfo<
      '/posts/"KMP模版"',
      '/posts/%22KMP%E6%A8%A1%E7%89%88%22',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/"Kruskal模版"': RouteRecordInfo<
      '/posts/"Kruskal模版"',
      '/posts/%22Kruskal%E6%A8%A1%E7%89%88%22',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/"Manacher模版"': RouteRecordInfo<
      '/posts/"Manacher模版"',
      '/posts/%22Manacher%E6%A8%A1%E7%89%88%22',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/"MCMF模版"': RouteRecordInfo<
      '/posts/"MCMF模版"',
      '/posts/%22MCMF%E6%A8%A1%E7%89%88%22',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/"SAM模版"': RouteRecordInfo<
      '/posts/"SAM模版"',
      '/posts/%22SAM%E6%A8%A1%E7%89%88%22',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/"ST表模版"': RouteRecordInfo<
      '/posts/"ST表模版"',
      '/posts/%22ST%E8%A1%A8%E6%A8%A1%E7%89%88%22',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/"Tarjan模版"': RouteRecordInfo<
      '/posts/"Tarjan模版"',
      '/posts/%22Tarjan%E6%A8%A1%E7%89%88%22',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/"TarjanEBCC模版"': RouteRecordInfo<
      '/posts/"TarjanEBCC模版"',
      '/posts/%22TarjanEBCC%E6%A8%A1%E7%89%88%22',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/"zkw线段树"': RouteRecordInfo<
      '/posts/"zkw线段树"',
      '/posts/%22zkw%E7%BA%BF%E6%AE%B5%E6%A0%91%22',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/“一些对于算法题的个人见解”': RouteRecordInfo<
      '/posts/“一些对于算法题的个人见解”',
      '/posts/%E2%80%9C%E4%B8%80%E4%BA%9B%E5%AF%B9%E4%BA%8E%E7%AE%97%E6%B3%95%E9%A2%98%E7%9A%84%E4%B8%AA%E4%BA%BA%E8%A7%81%E8%A7%A3%E2%80%9D',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/“关于Docker的一些个人理解”': RouteRecordInfo<
      '/posts/“关于Docker的一些个人理解”',
      '/posts/%E2%80%9C%E5%85%B3%E4%BA%8EDocker%E7%9A%84%E4%B8%80%E4%BA%9B%E4%B8%AA%E4%BA%BA%E7%90%86%E8%A7%A3%E2%80%9D',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/“如何连接IPv6的服务器”': RouteRecordInfo<
      '/posts/“如何连接IPv6的服务器”',
      '/posts/%E2%80%9C%E5%A6%82%E4%BD%95%E8%BF%9E%E6%8E%A5IPv6%E7%9A%84%E6%9C%8D%E5%8A%A1%E5%99%A8%E2%80%9D',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/“对于防御DDoS的一些思考”': RouteRecordInfo<
      '/posts/“对于防御DDoS的一些思考”',
      '/posts/%E2%80%9C%E5%AF%B9%E4%BA%8E%E9%98%B2%E5%BE%A1DDoS%E7%9A%84%E4%B8%80%E4%BA%9B%E6%80%9D%E8%80%83%E2%80%9D',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/“我的第一篇个人博客”': RouteRecordInfo<
      '/posts/“我的第一篇个人博客”',
      '/posts/%E2%80%9C%E6%88%91%E7%9A%84%E7%AC%AC%E4%B8%80%E7%AF%87%E4%B8%AA%E4%BA%BA%E5%8D%9A%E5%AE%A2%E2%80%9D',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/“解决clang无法使用万能头文件”': RouteRecordInfo<
      '/posts/“解决clang无法使用万能头文件”',
      '/posts/%E2%80%9C%E8%A7%A3%E5%86%B3clang%E6%97%A0%E6%B3%95%E4%BD%BF%E7%94%A8%E4%B8%87%E8%83%BD%E5%A4%B4%E6%96%87%E4%BB%B6%E2%80%9D',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/“CF题解——Not a Nim Problem”': RouteRecordInfo<
      '/posts/“CF题解——Not a Nim Problem”',
      '/posts/%E2%80%9CCF%E9%A2%98%E8%A7%A3%E2%80%94%E2%80%94Not%20a%20Nim%20Problem%E2%80%9D',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/关于DP的一些解题技巧': RouteRecordInfo<
      '/posts/关于DP的一些解题技巧',
      '/posts/%E5%85%B3%E4%BA%8EDP%E7%9A%84%E4%B8%80%E4%BA%9B%E8%A7%A3%E9%A2%98%E6%8A%80%E5%B7%A7',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/树上两点最值模版': RouteRecordInfo<
      '/posts/树上两点最值模版',
      '/posts/%E6%A0%91%E4%B8%8A%E4%B8%A4%E7%82%B9%E6%9C%80%E5%80%BC%E6%A8%A1%E7%89%88',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Atc的DP专训': RouteRecordInfo<
      '/posts/Atc的DP专训',
      '/posts/Atc%E7%9A%84DP%E4%B8%93%E8%AE%AD',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/CF题解——A and B and Lecture Rooms': RouteRecordInfo<
      '/posts/CF题解——A and B and Lecture Rooms',
      '/posts/CF%E9%A2%98%E8%A7%A3%E2%80%94%E2%80%94A%20and%20B%20and%20Lecture%20Rooms',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/CF题解——Ant colony': RouteRecordInfo<
      '/posts/CF题解——Ant colony',
      '/posts/CF%E9%A2%98%E8%A7%A3%E2%80%94%E2%80%94Ant%20colony',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/CF题解——Array Shrinking': RouteRecordInfo<
      '/posts/CF题解——Array Shrinking',
      '/posts/CF%E9%A2%98%E8%A7%A3%E2%80%94%E2%80%94Array%20Shrinking',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/CF题解——Binary Median': RouteRecordInfo<
      '/posts/CF题解——Binary Median',
      '/posts/CF%E9%A2%98%E8%A7%A3%E2%80%94%E2%80%94Binary%20Median',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/CF题解——Check Transcription': RouteRecordInfo<
      '/posts/CF题解——Check Transcription',
      '/posts/CF%E9%A2%98%E8%A7%A3%E2%80%94%E2%80%94Check%20Transcription',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/CF题解——Coloring Edges': RouteRecordInfo<
      '/posts/CF题解——Coloring Edges',
      '/posts/CF%E9%A2%98%E8%A7%A3%E2%80%94%E2%80%94Coloring%20Edges',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/CF题解——Distance to Different': RouteRecordInfo<
      '/posts/CF题解——Distance to Different',
      '/posts/CF%E9%A2%98%E8%A7%A3%E2%80%94%E2%80%94Distance%20to%20Different',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/CF题解——Dogeforces': RouteRecordInfo<
      '/posts/CF题解——Dogeforces',
      '/posts/CF%E9%A2%98%E8%A7%A3%E2%80%94%E2%80%94Dogeforces',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/CF题解——Frog Jumping': RouteRecordInfo<
      '/posts/CF题解——Frog Jumping',
      '/posts/CF%E9%A2%98%E8%A7%A3%E2%80%94%E2%80%94Frog%20Jumping',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/CF题解——Max Median': RouteRecordInfo<
      '/posts/CF题解——Max Median',
      '/posts/CF%E9%A2%98%E8%A7%A3%E2%80%94%E2%80%94Max%20Median',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/CF题解——Maximum Value': RouteRecordInfo<
      '/posts/CF题解——Maximum Value',
      '/posts/CF%E9%A2%98%E8%A7%A3%E2%80%94%E2%80%94Maximum%20Value',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/CF题解——Minimum Path': RouteRecordInfo<
      '/posts/CF题解——Minimum Path',
      '/posts/CF%E9%A2%98%E8%A7%A3%E2%80%94%E2%80%94Minimum%20Path',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/CF题解——Minimum spanning tree for each edge': RouteRecordInfo<
      '/posts/CF题解——Minimum spanning tree for each edge',
      '/posts/CF%E9%A2%98%E8%A7%A3%E2%80%94%E2%80%94Minimum%20spanning%20tree%20for%20each%20edge',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/CF题解——MST Unification': RouteRecordInfo<
      '/posts/CF题解——MST Unification',
      '/posts/CF%E9%A2%98%E8%A7%A3%E2%80%94%E2%80%94MST%20Unification',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/CF题解——One Occurrence': RouteRecordInfo<
      '/posts/CF题解——One Occurrence',
      '/posts/CF%E9%A2%98%E8%A7%A3%E2%80%94%E2%80%94One%20Occurrence',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/CF题解——OpenStreetMap': RouteRecordInfo<
      '/posts/CF题解——OpenStreetMap',
      '/posts/CF%E9%A2%98%E8%A7%A3%E2%80%94%E2%80%94OpenStreetMap',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/CF题解——Pathwalks': RouteRecordInfo<
      '/posts/CF题解——Pathwalks',
      '/posts/CF%E9%A2%98%E8%A7%A3%E2%80%94%E2%80%94Pathwalks',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/CF题解——Powerful array': RouteRecordInfo<
      '/posts/CF题解——Powerful array',
      '/posts/CF%E9%A2%98%E8%A7%A3%E2%80%94%E2%80%94Powerful%20array',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/CF题解——Present': RouteRecordInfo<
      '/posts/CF题解——Present',
      '/posts/CF%E9%A2%98%E8%A7%A3%E2%80%94%E2%80%94Present',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/CF题解——Remainder Problem': RouteRecordInfo<
      '/posts/CF题解——Remainder Problem',
      '/posts/CF%E9%A2%98%E8%A7%A3%E2%80%94%E2%80%94Remainder%20Problem',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/CF题解——Round Subset': RouteRecordInfo<
      '/posts/CF题解——Round Subset',
      '/posts/CF%E9%A2%98%E8%A7%A3%E2%80%94%E2%80%94Round%20Subset',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/CF题解——Shortest Path Problem': RouteRecordInfo<
      '/posts/CF题解——Shortest Path Problem',
      '/posts/CF%E9%A2%98%E8%A7%A3%E2%80%94%E2%80%94Shortest%20Path%20Problem',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/CF题解——Shovels Shop': RouteRecordInfo<
      '/posts/CF题解——Shovels Shop',
      '/posts/CF%E9%A2%98%E8%A7%A3%E2%80%94%E2%80%94Shovels%20Shop',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/CF题解——Tree Painting': RouteRecordInfo<
      '/posts/CF题解——Tree Painting',
      '/posts/CF%E9%A2%98%E8%A7%A3%E2%80%94%E2%80%94Tree%20Painting',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/CF题解——Two Editorials': RouteRecordInfo<
      '/posts/CF题解——Two Editorials',
      '/posts/CF%E9%A2%98%E8%A7%A3%E2%80%94%E2%80%94Two%20Editorials',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/CF题解——We Need More Bosses': RouteRecordInfo<
      '/posts/CF题解——We Need More Bosses',
      '/posts/CF%E9%A2%98%E8%A7%A3%E2%80%94%E2%80%94We%20Need%20More%20Bosses',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/CF题解——XOR and Favorite Number': RouteRecordInfo<
      '/posts/CF题解——XOR and Favorite Number',
      '/posts/CF%E9%A2%98%E8%A7%A3%E2%80%94%E2%80%94XOR%20and%20Favorite%20Number',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/CF题解——Xor Tree': RouteRecordInfo<
      '/posts/CF题解——Xor Tree',
      '/posts/CF%E9%A2%98%E8%A7%A3%E2%80%94%E2%80%94Xor%20Tree',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tags/': RouteRecordInfo<
      '/tags/',
      '/tags',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'node_modules/.pnpm/valaxy-theme-yun@0.26.13_magicast@0.5.4_vue@3.5.22_typescript@5.9.3_/node_modules/valaxy-theme-yun/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'node_modules/.pnpm/valaxy@1.0.0-rc.6_@babel+parser@7.29.8_@nuxt+kit@3.21.0_magicast@0.5.4__@types+markdown-it@14_msnibtdd5vxaej4oo4355743um/node_modules/valaxy/client/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
      pathParamNames:
        | 'path'
    }
    'pages/404.md': {
      routes:
        | '/404'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/about/index.md': {
      routes:
        | '/about/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/about/site.md': {
      routes:
        | '/about/site'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/archives/index.md': {
      routes:
        | '/archives/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/categories/index.md': {
      routes:
        | '/categories/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/links/index.md': {
      routes:
        | '/links/'
      views:
        | never
      pathParamNames:
        | never
    }
    'node_modules/.pnpm/valaxy-theme-yun@0.26.13_magicast@0.5.4_vue@3.5.22_typescript@5.9.3_/node_modules/valaxy-theme-yun/pages/page/[page].vue': {
      routes:
        | '/page/[page]'
      views:
        | never
      pathParamNames:
        | 'page'
    }
    'node_modules/.pnpm/valaxy-theme-yun@0.26.13_magicast@0.5.4_vue@3.5.22_typescript@5.9.3_/node_modules/valaxy-theme-yun/pages/posts/index.vue': {
      routes:
        | '/posts/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/"保持进程后台运行的实现方式".md': {
      routes:
        | '/posts/"保持进程后台运行的实现方式"'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/"关于C++的类内存泄漏相关".md': {
      routes:
        | '/posts/"关于C++的类内存泄漏相关"'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/"内网穿透简单教程".md': {
      routes:
        | '/posts/"内网穿透简单教程"'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/"可持久化线段树模版".md': {
      routes:
        | '/posts/"可持久化线段树模版"'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/"可撤销并查集模版".md': {
      routes:
        | '/posts/"可撤销并查集模版"'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/"哈希模版".md': {
      routes:
        | '/posts/"哈希模版"'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/"多色点对最短路优化方案".md': {
      routes:
        | '/posts/"多色点对最短路优化方案"'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/"矩阵快速幂模版".md': {
      routes:
        | '/posts/"矩阵快速幂模版"'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/"线性基模版".md': {
      routes:
        | '/posts/"线性基模版"'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/"线段树模版".md': {
      routes:
        | '/posts/"线段树模版"'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/"组合数模版".md': {
      routes:
        | '/posts/"组合数模版"'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/"莫队模版".md': {
      routes:
        | '/posts/"莫队模版"'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/"AC自动机模版".md': {
      routes:
        | '/posts/"AC自动机模版"'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/"CF题解——C. Beautiful Sequence".md': {
      routes:
        | '/posts/"CF题解——C. Beautiful Sequence"'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/"CF题解——C. Restricted Sorting".md': {
      routes:
        | '/posts/"CF题解——C. Restricted Sorting"'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/"CF题解——C. Serval and The Formula".md': {
      routes:
        | '/posts/"CF题解——C. Serval and The Formula"'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/"CF题解——C. Trip to the Olympiad".md': {
      routes:
        | '/posts/"CF题解——C. Trip to the Olympiad"'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/"CF题解——Canal Crossing".md': {
      routes:
        | '/posts/"CF题解——Canal Crossing"'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/"CF题解——Ceil Divisions".md': {
      routes:
        | '/posts/"CF题解——Ceil Divisions"'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/"CF题解——D. Boris and His".md': {
      routes:
        | '/posts/"CF题解——D. Boris and His"'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/"CF题解——D. Fibonacci Paths".md': {
      routes:
        | '/posts/"CF题解——D. Fibonacci Paths"'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/"CF题解——D. Max GEQ Sum".md': {
      routes:
        | '/posts/"CF题解——D. Max GEQ Sum"'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/"CF题解——D. Shohag Loves GCD".md': {
      routes:
        | '/posts/"CF题解——D. Shohag Loves GCD"'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/"CF题解——D2 .Max Sum OR (Hard Version)".md': {
      routes:
        | '/posts/"CF题解——D2 .Max Sum OR (Hard Version)"'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/"CF题解——Destroy it! ".md': {
      routes:
        | '/posts/"CF题解——Destroy it! "'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/"CF题解——E. Block Sequence".md': {
      routes:
        | '/posts/"CF题解——E. Block Sequence"'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/"CF题解——E. Calendar Ambiguity".md': {
      routes:
        | '/posts/"CF题解——E. Calendar Ambiguity"'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/"CF题解——E. Data Structures Fan".md': {
      routes:
        | '/posts/"CF题解——E. Data Structures Fan"'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/"CF题解——E. Graph Composition".md': {
      routes:
        | '/posts/"CF题解——E. Graph Composition"'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/"CF题解——E. Merging Towers".md': {
      routes:
        | '/posts/"CF题解——E. Merging Towers"'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/"CF题解——E. Power of Points".md': {
      routes:
        | '/posts/"CF题解——E. Power of Points"'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/"CF题解——E1. Eliminating Balls With Merging (Easy Version)".md': {
      routes:
        | '/posts/"CF题解——E1. Eliminating Balls With Merging (Easy Version)"'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/"CF题解——F. Final Boss".md': {
      routes:
        | '/posts/"CF题解——F. Final Boss"'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/"CF题解——F. SheriffsDefense".md': {
      routes:
        | '/posts/"CF题解——F. SheriffsDefense"'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/"CF题解——G. Garage".md': {
      routes:
        | '/posts/"CF题解——G. Garage"'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/"CF题解——Git Gud".md': {
      routes:
        | '/posts/"CF题解——Git Gud"'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/"CF题解——H. Beppa and SwerChat".md': {
      routes:
        | '/posts/"CF题解——H. Beppa and SwerChat"'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/"CF题解——Inversion Pairs".md': {
      routes:
        | '/posts/"CF题解——Inversion Pairs"'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/"CF题解——Juggling Keys".md': {
      routes:
        | '/posts/"CF题解——Juggling Keys"'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/"CF题解——Legacy".md': {
      routes:
        | '/posts/"CF题解——Legacy"'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/"CF题解——Lucky Country".md': {
      routes:
        | '/posts/"CF题解——Lucky Country"'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/"CF题解——Make It Increasing".md': {
      routes:
        | '/posts/"CF题解——Make It Increasing"'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/"CF题解——Petya and Graph".md': {
      routes:
        | '/posts/"CF题解——Petya and Graph"'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/"CF题解——Rearrange Brackets".md': {
      routes:
        | '/posts/"CF题解——Rearrange Brackets"'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/"CF题解——Shortest Path Queries".md': {
      routes:
        | '/posts/"CF题解——Shortest Path Queries"'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/"CF题解——Small GCD".md': {
      routes:
        | '/posts/"CF题解——Small GCD"'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/"CF题解——Tufurama".md': {
      routes:
        | '/posts/"CF题解——Tufurama"'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/"DInic模版".md': {
      routes:
        | '/posts/"DInic模版"'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/"DoubleHashMap模版".md': {
      routes:
        | '/posts/"DoubleHashMap模版"'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/"HopcroftKarp模版".md': {
      routes:
        | '/posts/"HopcroftKarp模版"'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/"J. Jewels Building".md': {
      routes:
        | '/posts/"J. Jewels Building"'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/"KMP模版".md': {
      routes:
        | '/posts/"KMP模版"'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/"Kruskal模版".md': {
      routes:
        | '/posts/"Kruskal模版"'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/"Manacher模版".md': {
      routes:
        | '/posts/"Manacher模版"'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/"MCMF模版".md': {
      routes:
        | '/posts/"MCMF模版"'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/"SAM模版".md': {
      routes:
        | '/posts/"SAM模版"'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/"ST表模版".md': {
      routes:
        | '/posts/"ST表模版"'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/"Tarjan模版".md': {
      routes:
        | '/posts/"Tarjan模版"'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/"TarjanEBCC模版".md': {
      routes:
        | '/posts/"TarjanEBCC模版"'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/"zkw线段树".md': {
      routes:
        | '/posts/"zkw线段树"'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/“一些对于算法题的个人见解”.md': {
      routes:
        | '/posts/“一些对于算法题的个人见解”'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/“关于Docker的一些个人理解”.md': {
      routes:
        | '/posts/“关于Docker的一些个人理解”'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/“如何连接IPv6的服务器”.md': {
      routes:
        | '/posts/“如何连接IPv6的服务器”'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/“对于防御DDoS的一些思考”.md': {
      routes:
        | '/posts/“对于防御DDoS的一些思考”'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/“我的第一篇个人博客”.md': {
      routes:
        | '/posts/“我的第一篇个人博客”'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/“解决clang无法使用万能头文件”.md': {
      routes:
        | '/posts/“解决clang无法使用万能头文件”'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/“CF题解——Not a Nim Problem”.md': {
      routes:
        | '/posts/“CF题解——Not a Nim Problem”'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/关于DP的一些解题技巧.md': {
      routes:
        | '/posts/关于DP的一些解题技巧'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/树上两点最值模版.md': {
      routes:
        | '/posts/树上两点最值模版'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/Atc的DP专训.md': {
      routes:
        | '/posts/Atc的DP专训'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/CF题解——A and B and Lecture Rooms.md': {
      routes:
        | '/posts/CF题解——A and B and Lecture Rooms'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/CF题解——Ant colony.md': {
      routes:
        | '/posts/CF题解——Ant colony'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/CF题解——Array Shrinking.md': {
      routes:
        | '/posts/CF题解——Array Shrinking'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/CF题解——Binary Median.md': {
      routes:
        | '/posts/CF题解——Binary Median'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/CF题解——Check Transcription.md': {
      routes:
        | '/posts/CF题解——Check Transcription'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/CF题解——Coloring Edges.md': {
      routes:
        | '/posts/CF题解——Coloring Edges'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/CF题解——Distance to Different.md': {
      routes:
        | '/posts/CF题解——Distance to Different'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/CF题解——Dogeforces.md': {
      routes:
        | '/posts/CF题解——Dogeforces'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/CF题解——Frog Jumping.md': {
      routes:
        | '/posts/CF题解——Frog Jumping'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/CF题解——Max Median.md': {
      routes:
        | '/posts/CF题解——Max Median'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/CF题解——Maximum Value.md': {
      routes:
        | '/posts/CF题解——Maximum Value'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/CF题解——Minimum Path.md': {
      routes:
        | '/posts/CF题解——Minimum Path'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/CF题解——Minimum spanning tree for each edge.md': {
      routes:
        | '/posts/CF题解——Minimum spanning tree for each edge'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/CF题解——MST Unification.md': {
      routes:
        | '/posts/CF题解——MST Unification'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/CF题解——One Occurrence.md': {
      routes:
        | '/posts/CF题解——One Occurrence'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/CF题解——OpenStreetMap.md': {
      routes:
        | '/posts/CF题解——OpenStreetMap'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/CF题解——Pathwalks.md': {
      routes:
        | '/posts/CF题解——Pathwalks'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/CF题解——Powerful array.md': {
      routes:
        | '/posts/CF题解——Powerful array'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/CF题解——Present.md': {
      routes:
        | '/posts/CF题解——Present'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/CF题解——Remainder Problem.md': {
      routes:
        | '/posts/CF题解——Remainder Problem'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/CF题解——Round Subset.md': {
      routes:
        | '/posts/CF题解——Round Subset'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/CF题解——Shortest Path Problem.md': {
      routes:
        | '/posts/CF题解——Shortest Path Problem'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/CF题解——Shovels Shop.md': {
      routes:
        | '/posts/CF题解——Shovels Shop'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/CF题解——Tree Painting.md': {
      routes:
        | '/posts/CF题解——Tree Painting'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/CF题解——Two Editorials.md': {
      routes:
        | '/posts/CF题解——Two Editorials'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/CF题解——We Need More Bosses.md': {
      routes:
        | '/posts/CF题解——We Need More Bosses'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/CF题解——XOR and Favorite Number.md': {
      routes:
        | '/posts/CF题解——XOR and Favorite Number'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/CF题解——Xor Tree.md': {
      routes:
        | '/posts/CF题解——Xor Tree'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/tags/index.md': {
      routes:
        | '/tags/'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
